name: locami
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  get: ^4.7.3
  http: ^1.6.0
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_ringtone_player: ^4.0.0+4
  audioplayers: ^6.1.1
  file_picker: ^8.1.4
  flutter_background_service: ^5.0.10
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  geocoding: ^4.0.0
  solar_icons: ^0.0.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_cache: ^1.5.2
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_file_store: ^1.2.3
  path_provider: ^2.1.5
  vibration: ^3.1.8
  home_widget: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
dependency_overrides:
  package_info_plus: 8.0.2
