name: Build and Release Locami

on:
  pull_request:
    branches:
      - release
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test

      - name: Build Release APK
        if: github.ref == 'refs/heads/release'
        run: flutter build apk --release --split-per-abi

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: locami-${{ github.run_number }}
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
